// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: document_parser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentParserService_ParsePDF_FullMethodName    = "/document_parser.DocumentParserService/ParsePDF"
	DocumentParserService_ParseDOCX_FullMethodName   = "/document_parser.DocumentParserService/ParseDOCX"
	DocumentParserService_HealthCheck_FullMethodName = "/document_parser.DocumentParserService/HealthCheck"
)

// DocumentParserServiceClient is the client API for DocumentParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 文档解析服务定义
type DocumentParserServiceClient interface {
	// 解析PDF文档
	ParsePDF(ctx context.Context, in *ParsePDFRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error)
	// 解析DOCX文档
	ParseDOCX(ctx context.Context, in *ParseDOCXRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type documentParserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentParserServiceClient(cc grpc.ClientConnInterface) DocumentParserServiceClient {
	return &documentParserServiceClient{cc}
}

func (c *documentParserServiceClient) ParsePDF(ctx context.Context, in *ParsePDFRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentParserService_ParsePDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentParserServiceClient) ParseDOCX(ctx context.Context, in *ParseDOCXRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentParserService_ParseDOCX_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentParserServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DocumentParserService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentParserServiceServer is the server API for DocumentParserService service.
// All implementations must embed UnimplementedDocumentParserServiceServer
// for forward compatibility.
//
// 文档解析服务定义
type DocumentParserServiceServer interface {
	// 解析PDF文档
	ParsePDF(context.Context, *ParsePDFRequest) (*ParseDocumentResponse, error)
	// 解析DOCX文档
	ParseDOCX(context.Context, *ParseDOCXRequest) (*ParseDocumentResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDocumentParserServiceServer()
}

// UnimplementedDocumentParserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentParserServiceServer struct{}

func (UnimplementedDocumentParserServiceServer) ParsePDF(context.Context, *ParsePDFRequest) (*ParseDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParsePDF not implemented")
}
func (UnimplementedDocumentParserServiceServer) ParseDOCX(context.Context, *ParseDOCXRequest) (*ParseDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseDOCX not implemented")
}
func (UnimplementedDocumentParserServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDocumentParserServiceServer) mustEmbedUnimplementedDocumentParserServiceServer() {}
func (UnimplementedDocumentParserServiceServer) testEmbeddedByValue()                               {}

// UnsafeDocumentParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentParserServiceServer will
// result in compilation errors.
type UnsafeDocumentParserServiceServer interface {
	mustEmbedUnimplementedDocumentParserServiceServer()
}

func RegisterDocumentParserServiceServer(s grpc.ServiceRegistrar, srv DocumentParserServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentParserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentParserService_ServiceDesc, srv)
}

func _DocumentParserService_ParsePDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParsePDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentParserServiceServer).ParsePDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentParserService_ParsePDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentParserServiceServer).ParsePDF(ctx, req.(*ParsePDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentParserService_ParseDOCX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseDOCXRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentParserServiceServer).ParseDOCX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentParserService_ParseDOCX_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentParserServiceServer).ParseDOCX(ctx, req.(*ParseDOCXRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentParserService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentParserServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentParserService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentParserServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentParserService_ServiceDesc is the grpc.ServiceDesc for DocumentParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document_parser.DocumentParserService",
	HandlerType: (*DocumentParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParsePDF",
			Handler:    _DocumentParserService_ParsePDF_Handler,
		},
		{
			MethodName: "ParseDOCX",
			Handler:    _DocumentParserService_ParseDOCX_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DocumentParserService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "document_parser.proto",
}
